modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = ""
[[mods]]
modId = "threadcontrol"
version = "1.0"
displayName = "Thread Control"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Simple mod that lets you control the amount of threads MC can use for different aspects of the game including: world gen, game start up, datapack loading.
'''
[[dependencies.threadcontrol]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
